
version: '3.7'
services:
  cl-binary-transformers-and-extractors:
    image: freelawproject/binary-transformers-and-extractors:latest
    container_name: "cl-binary-transformers-and-extractors"
    ports:
      - "80:80"
