
version: '3.7'

networks:
  cl_net_overlay:
    driver: bridge
    external: true

services:
  cl-binary-transformers-and-extractors:
    image: freelawproject/binary-transformers-and-extractors:latest
    container_name: "cl-binary-transformers-and-extractors"
    ports:
      - "80:80"
    networks:
      - cl_net_overlay
